### ISSUE TITLE
[REQ] embed "Show versions when installing or updating packages"

### ISSUE THREAD

**Issue by gps3dx** [Havoc-OS/android_packages_apps_PackageInstaller#1]
#enhancement request:
A really useful feature, that lately was added [to another pie rom](https://github.com/ResurrectionRemix/android_packages_apps_PackageInstaller/commit/847f9320d5743706a0cdade9cce5f701cabe8797) is the "Show versions when installing or updating packages".
AFAIK, that feature was in any CM based rom in the days of Nougat.

@SKULSHADY, Can you [please add it also ](https://github.com/ResurrectionRemix/android_packages_apps_PackageInstaller/commit/847f9320d5743706a0cdade9cce5f701cabe8797)to HAVOC-OS ?

Thanks.

**Comment by SKULSHADY** [comment]
LOL. We've had it since the beginning. Why comparing some 3rd grade rom to mine without even checking stuff first. Here's the commit https://github.com/Havoc-OS/android_packages_apps_PackageInstaller/commit/594a21b1890c9a75a14b22aa6e922ac8d836ca4e
